# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_article_title_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hide_title',
            field=models.BooleanField(default=False, verbose_name="Don't show the title in the final email."),
        ),
    ]
