# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_article_hide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
