# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='language',
            field=models.CharField(default='de', max_length=5, verbose_name='language'),
        ),
    ]
