# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-05 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20180108_1706'),
        ('newsletter', '0004_auto_20180407_1043'),
    ]

    operations = [
    ]
