# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_merge_20180505_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publish',
            field=models.BooleanField(db_index=True, default=False, help_text='Publish in archive.', verbose_name='publish'),
        ),
    ]
