# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20180521_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='newsletter',
            field=models.ForeignKey(default=newsletter.models.get_default_newsletter_pk, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Newsletter', verbose_name='newsletter'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publish',
            field=models.BooleanField(db_index=True, default=True, help_text='Publish in archive.', verbose_name='publish'),
        ),
    ]
