# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20180522_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='F\xfcr lokale Verlinkungen innerhalb des Newsletter (optional)', max_length=200, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, help_text='Ein "Read More"-Link z.B. auf eine Webseite.', null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publish',
            field=models.BooleanField(db_index=True, default=False, help_text='Publish in archive.', verbose_name='publish'),
        ),
    ]
