# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0014_auto_20180604_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('user', 'newsletter'), ('email_field', 'newsletter')]),
        ),
    ]
