# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0015_auto_20180604_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='send at'),
        ),
    ]
