# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_auto_20180723_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='publish',
            field=models.BooleanField(db_index=True, default=True, help_text='Publish in archive.', verbose_name='publish'),
        ),
    ]
