# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0017_auto_20181112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publish',
            field=models.BooleanField(db_index=True, default=False, help_text='Publish in archive.', verbose_name='publish'),
        ),
    ]
